print("**************************")
print("*                        *")
print("*        计算器          *")
print("* 请输入算式按回车键结束 *")
print("*                        *")
print("**************************")
x=input("->")
y=eval(x)
print(x+"="+ str(y))
